
exclude: .+/migrations/.+\.py
repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=0, -v]
        exclude: ^(docs/conf.py|setup.py)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.27.0
    hooks:
      - id: pyupgrade